from django.db import models

# Create your models here.
class appform1(models.Model):
    fname=models.CharField(max_length=120)
    lname=models.CharField(max_length=120)
    email=models.EmailField(max_length=50)
    contact_number=models.CharField(max_length=20)
    aadhar_number = models.CharField(max_length=20)
    quo=models.CharField(max_length=20,null=True)
    category = models.CharField(max_length=10)
    dob = models.DateField()
    gender = models.CharField(max_length=7)
    boe = models.CharField(max_length=7)
    year = models.CharField(max_length=4)
    result = models.CharField(max_length=10)
    brno = models.CharField(max_length=120,default=0000)
    mothna = models.CharField(max_length=120)
    mothc = models.CharField(max_length=120)
    motho = models.CharField(max_length=120)
    fathna = models.CharField(max_length=120)
    fathc = models.CharField(max_length=120)
    fatho = models.CharField(max_length=120)
    ques = models.CharField(max_length=13)
    add1 = models.CharField(max_length=120)
    add2 = models.CharField(max_length=120)
    country = models.CharField(max_length=20)
    state = models.CharField(max_length=20)
    city = models.CharField(max_length=20)
    pincode = models.CharField(max_length=20)
    padd1 = models.CharField(max_length=120)
    padd2 = models.CharField(max_length=120)
    pcountry = models.CharField(max_length=120)
    pstate = models.CharField(max_length=120)
    pcity = models.CharField(max_length=120)
    ppincode = models.CharField(max_length=120)
    bank = models.CharField(max_length=120)
    accn = models.CharField(max_length=20)
    accno = models.CharField(max_length=20)
    ifs = models.CharField(max_length=20)
    photo = models.FileField(upload_to='images/')
    sign = models.FileField(upload_to='images/')
    mark = models.FileField(upload_to='images/')
    

    def __str__(self):
        return self.fname