# Generated by Django 2.1 on 2018-10-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appform',
            name='aadhar_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appform',
            name='contact_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appform',
            name='pincode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appform',
            name='ppincode',
            field=models.IntegerField(),
        ),
    ]
