# Generated by Django 2.1 on 2018-10-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20181029_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appform1',
            name='roll',
        ),
        migrations.AddField(
            model_name='appform1',
            name='brno',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
