# Generated by Django 2.1 on 2018-10-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20181029_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='appform1',
            name='quo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
