# Generated by Django 2.1 on 2018-10-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_appform1_quo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appform1',
            name='mark',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='appform1',
            name='photo',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='appform1',
            name='sign',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
