# Generated by Django 2.0.6 on 2018-10-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_auto_20181029_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appform1',
            name='bank',
            field=models.CharField(max_length=120),
        ),
    ]
